export type NotificationSegment = 'Users' | 'CSP'

export type Notification = {
  id: string
  sender: string
  senderEmail: string
  avatar?: string
  isSystem?: boolean
  segment: NotificationSegment
  pushSent: boolean
  title: string
  preview: string
  sentDate: string
}

export const NOTIFICATIONS_TOTAL = 390

export const notifications: Notification[] = [
  {
    id: 'NTF001',
    sender: 'Vladislava Kotova',
    senderEmail: 'v.kotova@mediacube.io',
    segment: 'Users',
    pushSent: true,
    title: 'Important Update: Withdrawal Fee Changes Effective July 6, 2026',
    preview: 'Dear User, We are writing to inform you of an upcoming change to the fee for fund withdrawals.',
    sentDate: '02 Jul 2026',
  },
  {
    id: 'NTF002',
    sender: 'Andrei Vasileuski',
    senderEmail: 'andre@mediacube.io',
    isSystem: true,
    segment: 'Users',
    pushSent: true,
    title: 'Perks and Benefits in Garna',
    preview: "We know how much of your budget goes toward work tools, so we've negotiated exclusive discounts.",
    sentDate: '01 Jul 2026',
  },
  {
    id: 'NTF003',
    sender: 'Maria Lapchik G',
    senderEmail: 'lapm@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: 'Hi! We are delighted to welcome you to the Garna platform!',
    preview: 'Your profile has been successfully registered. Your account is now officially linked to Life.',
    sentDate: '26 Jun 2026',
  },
  {
    id: 'NTF004',
    sender: 'Maria Lapchik G',
    senderEmail: 'lapm@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: 'Hi! We are delighted to welcome you to the Garna platform!',
    preview: 'Your profile has been successfully registered. Your account is now officially linked to Life.',
    sentDate: '26 Jun 2026',
  },
  {
    id: 'NTF005',
    sender: 'Maria Lapchik G',
    senderEmail: 'lapm@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: 'Добрый день! Рады приветствовать вас на платформе Garna!',
    preview: 'Ваш профиль успешно зарегистрирован. Мы рады сообщить, что ваш аккаунт официально привязан.',
    sentDate: '26 Jun 2026',
  },
  {
    id: 'NTF006',
    sender: 'Maria Lapchik G',
    senderEmail: 'lapm@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: 'Добрый день! Рады приветствовать вас на платформе Garna!',
    preview: 'Ваш профиль успешно зарегистрирован. Мы рады сообщить, что ваш аккаунт официально привязан.',
    sentDate: '26 Jun 2026',
  },
  {
    id: 'NTF007',
    sender: 'Alesia Marchuk',
    senderEmail: 'almar@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: 'Scheduled Maintenance',
    preview: 'On June 24, from 08:00 to 13:00 UTC, crypto withdrawals will be unavailable. This is a planned update.',
    sentDate: '23 Jun 2026',
  },
  {
    id: 'NTF008',
    sender: 'KaterinaQ Kot',
    senderEmail: 'em@mediacube.io',
    segment: 'Users',
    pushSent: false,
    title: 'e',
    preview: 'тест',
    sentDate: '26 May 2026',
  },
  {
    id: 'NTF009',
    sender: 'Evgeniia Frolenkova',
    senderEmail: 'fro@mediacube.io',
    segment: 'Users',
    pushSent: true,
    title: 'Your Advance is waiting — check it now',
    preview: 'Get an Advance for up to 12 months — calculate amount in MC Pay',
    sentDate: '14 May 2026',
  },
  {
    id: 'NTF010',
    sender: 'Alesia Marchuk',
    senderEmail: 'almar@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: 'Crypto wallet terms update',
    preview: 'Starting May 15, 2026, an inactivity fee of 200 USD/month will apply to wallets with no activity.',
    sentDate: '12 May 2026',
  },
  {
    id: 'NTF011',
    sender: 'Maksim Trafimau',
    senderEmail: 'maxtro@mediacube.io',
    segment: 'CSP',
    pushSent: false,
    title: 'YouTube payout information update',
    preview: 'Due to temporary delays in receiving funds from YouTube and completing the required checks.',
    sentDate: '08 May 2026',
  },
  {
    id: 'NTF012',
    sender: 'Alesia Marchuk',
    senderEmail: 'almar@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: 'Изменения выплат в RUB',
    preview: 'В связи с санкционными ограничениями с 14 мая прекращаются выплаты на счета в РФ.',
    sentDate: '06 May 2026',
  },
  {
    id: 'NTF013',
    sender: 'Vladislav Filipovich G',
    senderEmail: 'filv@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: 'Crypto withdrawal fee update',
    preview: 'Starting May 1, 2026, the crypto withdrawal fee will increase by a fixed 5 USD on top of the network fee.',
    sentDate: '05 May 2026',
  },
  {
    id: 'NTF014',
    sender: 'Vladislav Filipovich G',
    senderEmail: 'filv@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: "We'd like to share a few important updates with you",
    preview: 'Changes in the list of banks available for withdrawals in Russia and crypto withdrawal fee update.',
    sentDate: '05 May 2026',
  },
  {
    id: 'NTF015',
    sender: 'Vladislav Filipovich G',
    senderEmail: 'filv@mediacube.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=80&h=80&q=80',
    segment: 'Users',
    pushSent: true,
    title: "We'd like to share a few important updates with you",
    preview: 'Changes in Belarusian banking operations and crypto withdrawal fee update.',
    sentDate: '05 May 2026',
  },
]
