export type PromotionSegment = 'Users' | 'CSP'

export type Promotion = {
  id: string
  name: string
  segment: PromotionSegment
  countries: string
  leadsTo: string
  endDate?: string
  updated: string
  serial: number
  title: string
  text: string
  buttonText: string
}

export const promotions: Promotion[] = [
  {
    id: 'p1',
    name: 'Save on Services with Garna',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '09 Jul 2026',
    serial: 1,
    title: 'Save on Services with Garna',
    text: 'Get discounts on selected services when you top up your Garna balance.',
    buttonText: 'Go to balance',
  },
  {
    id: 'p2',
    name: 'Update your mobile app',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '09 Jul 2026',
    serial: 2,
    title: 'Update your mobile app',
    text: 'A new version of the app is available with faster payouts and a cleaner inbox.',
    buttonText: 'Update now',
  },
  {
    id: 'p3',
    name: 'FAQ: Service Update',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '09 Jul 2026',
    serial: 3,
    title: 'FAQ: Service Update',
    text: 'Read the latest answers about the service update and how it affects your account.',
    buttonText: 'Open FAQ',
  },
  {
    id: 'p4',
    name: 'How to create an offer?',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '09 Jul 2026',
    serial: 4,
    title: 'How to create an offer?',
    text: 'A short guide to creating and publishing an offer in a few steps.',
    buttonText: 'Start',
  },
  {
    id: 'p5',
    name: 'New payout options',
    segment: 'CSP',
    countries: 'Kazakhstan +2',
    leadsTo: 'balance',
    updated: '02 Jul 2026',
    serial: 5,
    title: 'New payout options',
    text: 'Partners in selected countries can now choose extra payout methods.',
    buttonText: 'View options',
  },
  {
    id: 'p6',
    name: 'Summer campaign for partners',
    segment: 'CSP',
    countries: 'Russia +2',
    leadsTo: 'balance',
    updated: '28 Jun 2026',
    serial: 6,
    title: 'Summer campaign for partners',
    text: 'Join the seasonal campaign and unlock extra rewards for active partners.',
    buttonText: 'Join campaign',
  },
  {
    id: 'p7',
    name: 'Verify your account',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '21 Jun 2026',
    serial: 7,
    title: 'Verify your account',
    text: 'Complete KYC to unlock higher limits and faster withdrawals.',
    buttonText: 'Verify',
  },
  {
    id: 'p8',
    name: 'Referral bonus is live',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '18 Jun 2026',
    serial: 8,
    title: 'Referral bonus is live',
    text: 'Invite creators and get a bonus after their first successful payout.',
    buttonText: 'Invite friends',
  },
  {
    id: 'p9',
    name: 'Contract signing reminder',
    segment: 'CSP',
    countries: 'Kazakhstan +2',
    leadsTo: 'balance',
    updated: '12 Jun 2026',
    serial: 9,
    title: 'Contract signing reminder',
    text: 'Please sign the updated ICA to keep access to payouts.',
    buttonText: 'Open contract',
  },
  {
    id: 'p10',
    name: 'App onboarding tips',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '04 Jun 2026',
    serial: 10,
    title: 'App onboarding tips',
    text: 'Three tips to set up notifications, channels and payouts.',
    buttonText: 'Got it',
  },
  {
    id: 'p11',
    name: 'Holiday schedule',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '22 May 2026',
    serial: 11,
    title: 'Holiday schedule',
    text: 'Payout processing may take longer during the holiday period.',
    buttonText: 'See dates',
  },
  {
    id: 'p12',
    name: 'Partner dashboard update',
    segment: 'CSP',
    countries: 'Russia +2',
    leadsTo: 'balance',
    updated: '14 May 2026',
    serial: 12,
    title: 'Partner dashboard update',
    text: 'Analytics and request filters now load faster in the partner dashboard.',
    buttonText: 'Open dashboard',
  },
  {
    id: 'p13',
    name: 'Enable 2FA',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '02 May 2026',
    serial: 13,
    title: 'Enable 2FA',
    text: 'Protect your account with two-factor authentication.',
    buttonText: 'Enable',
  },
  {
    id: 'p14',
    name: 'Advance request window',
    segment: 'CSP',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '18 Apr 2026',
    serial: 14,
    title: 'Advance request window',
    text: 'The next advance request window opens this Friday.',
    buttonText: 'Learn more',
  },
  {
    id: 'p15',
    name: 'New countries available',
    segment: 'Users',
    countries: 'Kazakhstan +2',
    leadsTo: 'balance',
    updated: '03 Apr 2026',
    serial: 15,
    title: 'New countries available',
    text: 'Payouts are now available in additional countries.',
    buttonText: 'Check availability',
  },
  {
    id: 'p16',
    name: 'Balance top-up bonus',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '21 Mar 2026',
    serial: 16,
    title: 'Balance top-up bonus',
    text: 'Top up your balance this week and receive a limited bonus.',
    buttonText: 'Top up',
  },
  {
    id: 'p17',
    name: 'Welcome to Garna',
    segment: 'Users',
    countries: 'All countries',
    leadsTo: 'balance',
    updated: '11 Mar 2026',
    serial: 17,
    title: 'Welcome to Garna',
    text: 'Start with a short tour of channels, payouts and support.',
    buttonText: 'Start tour',
  },
]
